// <auto-generated />
using System;
using BookRental.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookRental.NET.Migrations
{
    [DbContext(typeof(BookRentalDbContext))]
    [Migration("20230420132140_RemoveForeignKeysToReservations")]
    partial class RemoveForeignKeysToReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookRental.NET.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George R. R. Martin",
                            ISBN = "1234-5678-4200",
                            Title = "Knight of the Seven Kingdoms"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Leigh Bardugo",
                            ISBN = "8972-2387-2873",
                            Title = "Shadow and Bone"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J. R. R. Tolkien",
                            ISBN = "2890-5498-1283",
                            Title = "Lord of the Rings"
                        });
                });

            modelBuilder.Entity("BookRental.NET.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "WTAdmin@WT.com",
                            IsAdmin = true,
                            Location = "Oostzaan",
                            Name = "Admin WT",
                            Password = "admin",
                            PhoneNumber = "1234",
                            StartingDate = new DateTime(2023, 4, 20, 15, 21, 40, 856, DateTimeKind.Local).AddTicks(2083),
                            Token = ""
                        },
                        new
                        {
                            Id = 2,
                            Email = "WTIntern@WT.com",
                            IsAdmin = false,
                            Location = "Groningen",
                            Name = "Intern WT",
                            Password = "intern",
                            PhoneNumber = "5678",
                            StartingDate = new DateTime(2023, 4, 20, 15, 21, 40, 856, DateTimeKind.Local).AddTicks(2126),
                            Token = ""
                        },
                        new
                        {
                            Id = 3,
                            Email = "Client@ClientCompany.com",
                            IsAdmin = false,
                            Location = "Amsterdam",
                            Name = "Client User",
                            Password = "client",
                            PhoneNumber = "password",
                            StartingDate = new DateTime(2023, 4, 20, 15, 21, 40, 856, DateTimeKind.Local).AddTicks(2129),
                            Token = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
